### ISSUE TITLE
Different ammo types

### ISSUE THREAD

**Issue by ADM8** [WeaponMechanics/MechanicsMain#53] opened 2022-03-15 19:15 UTC
### Description

Different ammo types that can be used on the same gun, things like poison bullets, incindeary shells, ap and he rockets, etc.
one gun can reload a different ammo type that changes stats like recoil, damage, trajectory, etc.

### Configuration

use advanced ammos: true
insert gun here:
possible_ammos:
.45, .45_poison, .45_fire

then instead of a weapon config for details like recoil, damage, etc. there are ammo configs.

**Comment by CJCrafter** [comment] 2022-11-20 01:37
Duplicate of #62

**Closed by CJCrafter** 2022-11-20 01:37 UTC
Labels: enhancement, duplicate
