### ISSUE TITLE
Damage pierces armor per gun

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#74] opened 2022-04-22 16:31 UTC
### Description

Right now you can edit damage done VS armor in config.yml, but what if I made a special gun or future attachment that has Armor Piercing rounds?
Basically, a simple option per gun to simply ignore armor.

### Configuration

```yaml
  Damage:
    Ignore_Armor: <true/false>
```

**Comment by CJCrafter** [comment] 2022-08-31 04:20
Duplicate of #139

**Closed by CJCrafter** 2022-08-31 04:20 UTC
Labels: enhancement, will add
