### ISSUE TITLE
Strange vertical knockback with some weapons

### ISSUE THREAD

**Issue by Fredh1000** [WeaponMechanics/MechanicsMain#379] opened 2023-12-11 11:44 UTC
### Current/Expected Behavior

In the 1.8.8 (server version) + CrackShot, the vertical knockback of the weapons is totally different than in the 1.20.2 + WeaponsMechanics (or CrackShot) and, in general, in the modern version + WeaponsMechanics (or CrackShot).
The vertical KB in 1.8.8 with old weapons is always applied and not only when I am below the height of the target.
To explain the problem better, I show you these 2 recordings:
1) 1.8.8 with CrackShot: https://www.youtube.com/watch?v=cCBddfwBlsE
2) 1.20.2 with WeaponsMechanics (CrackShot has the same problem): https://www.youtube.com/watch?v=bo_MiChaf2s
3) 1.16.5 with CrackShot (same problem): https://www.youtube.com/watch?v=EJGG_QtqgQE
I hope this problem can be resolved, because I haven't found a way to fix it yet.
The config I used: 
[Test.txt](https://github.com/WeaponMechanics/MechanicsMain/files/13634878/Test.txt)

### Steps To Reproduce

1) Use the config that I provided.
2) Start the server with newer version.
3) Than you see the same KB in the video 2.

### Log File

No required

**Comment by Fredh1000** [comment] 2023-12-12 05:14
Sorry for my miscommunication, I didn't mean that, I already know that.
What causes problems is the knockback itself, I would like it to be like the one in the video with CrackShot on a 1.8.8 server and not like the one in the other 2 videos (which is strange), I don't know if it's feasible or fixable in any way.

**Comment by CJCrafter** [comment] 2024-01-01 19:10
If you want to replicate the vanilla knockback system, you can enable it in the config.yml.

Marking this as solved, as it is not a bug. Use discord for support.

**Closed by CJCrafter** 2024-01-01 19:10 UTC
Labels: bug
