### ISSUE TITLE
no drops on die

### ISSUE THREAD

**Issue by AycanKanar** [WeaponMechanics/MechanicsMain#329] opened 2023-06-24 15:03 UTC
### Description

hi, sorry my english is bad.
if is possible i suggest an line to set a weapon dropable on die or not
tanks you and your plugins is very nice ^^

### Configuration

```yaml
Cancel:
  drop_on_die: <true/false>
```

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by yum13241** [comment] 2023-06-25 13:05
Can't you use the vanilla gamerule for this? (keepInventory)

**Comment by CJCrafter** [comment] 2023-06-30 00:09
duplicate of #117

**Closed by CJCrafter** 2023-06-30 00:09 UTC
Labels: enhancement, new

**Comment by AycanKanar** [comment] 2023-06-30 01:09
Hi, i dont know if i can because i need to create certain weapon dropable when the player dead and not for other weapon, i creating a game when you are New you have basicaly weapon and if you die is drop, but when you kill other payer you earn money with this money you can buy beter weapon undropable. Thanks for helping me i serached how i can do it but in vanilla or with other plugin is impossible because i use item meta data.
