### ISSUE TITLE
Delay_Between_Shots bug

### ISSUE THREAD

**Issue by kyou0419** [WeaponMechanics/MechanicsMain#359] opened 2023-09-21 15:21 UTC
### Current Behavior

Change weapons with [Delay_Between_Shots] set.

### Expected Behavior

I would like to have separate Delay_Between_Shots values for each weapon, so that WeaponB can strike immediately after WeaponA is fired.

I'm using a translation, so the sentence may be strange.

### Steps To Reproduce

1.Create two weapons with Delay_Between_Shots set.
(It may be easier to understand if Delay_Between_Shots is set to about 5 seconds.)
2.After shooting one weapon, bring it back to the other.

### Version and Log

1.20.1

### Anything else?

https://drive.google.com/file/d/1ackmkKKb1U8L70sE12E0D4A7LukqsT3n/view?usp=sharing

**Comment by CJCrafter** [comment] 2023-09-21 15:24
Duplicate of #148

**Closed by CJCrafter** 2023-09-21 15:24 UTC
Labels: bug

**Comment by kyou0419** [comment] 2023-09-22 07:38
By not looking closely at #148 I was doing something wrong.
Sorry for making you feel bad.
