### ISSUE TITLE
Per bullet magazine ammo system

### ISSUE THREAD

**Issue by zunkerman** [WeaponMechanics/MechanicsMain#376] opened 2023-11-29 05:17 UTC
### Description

I'd like a new ammo system for mag based ammo. Instead of reloading a mag missing 1 bullet and losing all of that ammo, it will give you that ammo back in a new magazine.

-reloading a gun that isn't empty will generate a new version of the ammo item that displays how much ammo is left in it
-ammo could display left over ammo by using the vanilla durability bar, for example a 15/30 magazine would show as half broken
-players could combine mags by clicking them together, going over the magazines limit would make a full mag and a new mag with the leftovers, for example 2 20/30 magazines combining to make a 30/30 and 10/30 magazine
-option for keeping the feature that reloading a brand new mag generated with /wm ammo will still completely reload the gun, but also the ability to make mags with forced max ammo quantities, like a magazine that can only reload up to 30 bullets if generated from a gun with a max magazine size of 30
-reloading a gun will prioritize the most full mag

### Configuration

Ammo details:
   ammo-system: magazine
   force-match: true/false

### Payment (optional)

- [X] I'm willing to pay for this feature

**Comment by CJCrafter** [comment] 2023-12-02 18:57
duplicate of #271, an issue that you yourself opened.

**Closed by CJCrafter** 2023-12-02 18:57 UTC
Labels: enhancement
